// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import { guards as autoguard } from "@joelek/ts-autoguard";

export type FormatResult = {
	"format": {
		"duration": string,
		"tags": {
			"title": string,
			"artist": string,
			"replaygain_track_gain"?: string,
			"replaygain_track_peak"?: string
		}
	}
};

export const FormatResult = autoguard.Object.of<FormatResult>({
	"format": autoguard.Object.of<{
		"duration": string,
		"tags": {
			"title": string,
			"artist": string,
			"replaygain_track_gain"?: string,
			"replaygain_track_peak"?: string
		}
	}>({
		"duration": autoguard.String,
		"tags": autoguard.Object.of<{
			"title": string,
			"artist": string,
			"replaygain_track_gain"?: string,
			"replaygain_track_peak"?: string
		}>({
			"title": autoguard.String,
			"artist": autoguard.String,
			"replaygain_track_gain": autoguard.Union.of(
				autoguard.Undefined,
				autoguard.String
			),
			"replaygain_track_peak": autoguard.Union.of(
				autoguard.Undefined,
				autoguard.String
			)
		})
	})
});

export type Autoguard = {
	"FormatResult": FormatResult
};

export const Autoguard = {
	"FormatResult": FormatResult
};
